### ISSUE TITLE
Sparkle AutoUpdate.app requires admin

### ISSUE THREAD

**Issue by gaocan1992** [sparkle-project/Sparkle#1219] opened 2018-04-24 06:28 UTC
Before I used Sparkle framework without any problem but now since I want to make a custom Sparkle build, I have built a release version of Sparkle using Sparkle 1.18.1 and replace the old sparkle framework in my project with this.
But now the AutoUpdate.app requires admin. Any idea why it happened?
![autoupdate](https://user-images.githubusercontent.com/11251559/39169774-eff9a3b2-474d-11e8-8984-ab24ea1232b6.jpeg)

**Comment by gaocan1992** [comment] 2018-04-24 22:02
@kornelski I investigated the app bundle's permission. 
If I drag & drop this app into Applications folder the AutoUpdate.app won't pop up that permission window.
If I use pkg installer to install the app in Applications folder then it requires admin for AutoUpdate.app.
The difference I found is that the first app bundle has "admin Read Only permission" but the later one has "wheel Read Only permission".
Both have "{current user} Read & Write permission" and "everyone Read permission"

**Comment by jkbullard** [comment] 2018-04-24 22:41
Aren't you supposed to specify the ownership and permissions of each file in a pkg install when you make the pkg -- either implicitly from the ownership/permissions on the files from which the pkg is created, or explicitly in a post-install script? (Folder ownership/permissions are also set this way, I think.)

**Comment by gaocan1992** [comment] 2018-04-24 22:46
@jkbullard 
In my post-install script ($2 - Target location)
I have this permission setting:

```
chown -R "$USER" "$2"

do sudo -E -u "$USER" open "$2"
```

**Comment by gaocan1992** [comment] 2018-04-24 22:59
maybe a same issue https://github.com/sparkle-project/Sparkle/issues/752

**Comment by jkbullard** [comment] 2018-04-24 22:59
@gaocan1992 - I'm not an expert on pkgs, but you aren't specifically setting the _group_ ownership.

Maybe you need something like
```
chown -R "$USER:staff" "$2"
```

(Looking at my /Applications folder, some apps are $USER:staff, some are $USER:admin, some are root:wheel.)

**Comment by jkbullard** [comment] 2018-04-24 23:02
@gaocan1992 - My understanding is that a "standard" user can't change apps that are $user:admin, but can change apps that are $user:staff, but I'm not certain about it.

**Comment by gaocan1992** [comment] 2018-04-24 23:05
@jkbullard 
Looks like it works, I will make some tests.

**Comment by gaocan1992** [comment] 2018-04-26 00:47
@jkbullard 
Today I am testing it using a Guest account of my Mac then it happened again.
Is that because my Guest account is not considered as a standard user?
You said that _a "standard" user can change apps that are $user:staff_

**Comment by kornelski** [comment] 2018-04-26 01:03
Yes. Guests shouldn't be able to replace applications.

**Comment by gaocan1992** [comment] 2018-04-26 16:58
@kornelski But is that possible to give guests permission to replace applications?

**Comment by kornelski** [comment] 2018-04-26 17:29
Yes, you can make them read & write for everyone.

**Comment by gaocan1992** [comment] 2018-04-26 22:09
@kornelski I have done that like you suggested and I also think it is the way to go:

<img width="240" alt="screen shot 2018-04-26 at 3 08 09 pm" src="https://user-images.githubusercontent.com/11251559/39334513-bf7487bc-4963-11e8-943f-07eb1b499a25.png">

But for my guest account when it updates it still pops up that window asking admin password.

**Comment by gaocan1992** [comment] 2018-04-27 02:13
@kornelski I found for non-admin user, you won't see this popup only if you install this app in user's home directory which is `~/Applications` or `$HOME/Applications` folder instead of the root `/Applications` folder

And this is not suggested [Making OS X Installer Packages like a Pro](https://stackoverflow.com/questions/11487596/making-os-x-installer-packages-like-a-pro-xcode-developer-id-ready-pkg)

Also I couldn't find a way to install it to user's home directory folder.
If you expand a pkg file using `pkgutil --expand` you will see there is a file called PackageInfo

Inside it contains a static field called install-location.
But for pkg installer I do notice that there is a step called **"Destination Select"** but I am not sure how to modify it using `pkgbuild` to choose user's home directory if it is possible.

**Comment by kornelski** [comment] 2018-04-29 12:40
Please try this release:

https://github.com/sparkle-project/Sparkle/releases/tag/1.19.1a1

and check the logs for "Sparkle: Authorization required to" […], which will explain why it things authorization is needed.

**Comment by gaocan1992** [comment] 2018-04-30 18:14
@kornelski Great suggestion!

**Comment by Offirmo** [comment] 2018-05-21 00:49
Hi. I had such a popup today, but I can't identify the app which is triggering it. 
Since I have no "autoupdate" app installed, that makes the popup suspicious.
Could the popup at least mention the app which caused it to appear?

**Comment by kornelski** [comment] 2018-05-21 11:04
@Offirmo Yes, we've fixed this already. The current version of Sparkle says which application is requesting the update. 

You will be seeing the old message until authors update Sparkle in their apps, and you update the apps to the version with newer Sparkle.

**Comment by Offirmo** [comment] 2018-06-08 07:31
Awesome!

**Comment by antoineazar** [comment] 2019-06-19 21:49
Hey all, getting the same issue here: any standard user CANNOT get the app to update in the background. I also might be blind but I can't find in Console any information. Any help would be appreciated.

**Comment by gaocan1992** [comment] 2019-06-24 20:24
@antoineazar 
Try set NSUserDefaults StandardUserDefaults in run time.
Make SUEnableAutomaticChecks, SUAllowsAutomaticUpdates and SUAutomaticallyUpdate to true.
See if it helps.

**Comment by zorgiepoo** [comment] 2021-03-22 18:27
Not silently installing an update that requires user to authorize for update works as designed. Closing out as I believe issues here are addressed, or they need to be re-reported.

**Closed by zorgiepoo** 2021-03-22 18:27 UTC
