### ISSUE TITLE
generate_appcast seems to completely overwhelm my system when there are a lot of packages

### ISSUE THREAD

**Issue by kode54** [sparkle-project/Sparkle#1719] opened 2021-01-10 05:02 UTC
I have a huge backlog of old versions stored locally for my project, Cog. Prior to my cleanup, I had over 200 release ZIPs in the release directory that generate_appcast scans, and 234 cache folders in the cache folder, each containing fully unpacked .app bundles.

For some reason, generate_appcast is not content to simply read the appcast xml file and find which archives in the work directory have not been processed. Apparently, it must scan over my entire archive set, every single time it runs. This scanning was eating all 16 threads of my CPU, and munching away at about 1.2GB/s read speed of my SSD.

I had to terminate it, only to find it had only just started generating a single delta. I had to prune all the release versions older than 60 days, and delete the entire cache, to bring it under control.

**Comment by kornelski** [comment] 2021-01-10 15:01
It's meant to cache unarchived folders. It should be doing the heavy work once (at least until you clear Library/Caches)

It does use all cores on purpose. Why keep them idle and make processing slower? On Intel, Turbo boost will use maximum power/heat no matter how many cores you use.

And 1.2GB/s is a low utilisation when SSDs can do over 3GB/s these days :)

It needs to read all Info.plist files to get accurate version info. In case of ZIP it could be faster indeed, but it can't do much about tar or DMG which don't have random access. And for compatibility and simplicity it just reuses Sparkle's standard unarchiver. And then it needs all files for deltas.

**Comment by kode54** [comment] 2022-07-07 02:02
It also seems to use upwards of 11GB of RAM to generate the deltas for 5 historical versions, for an app bundle of about 84.9MB. My Sparkle_generate_appcast folder has reached 334 archive folders extracted, which was 27GB, but I reduced it to 12GB by applying afsctool to the entire folder.

**Comment by kode54** [comment] 2022-07-07 02:05
It doesn't help that sometimes I make 5 releases or more in a day, because I commit an emergency change, then immediately roll out a release.

**Comment by zorgiepoo** [comment] 2022-07-07 06:12
Are you able to profile and see where it's taking most time and memory?

Just want to make sure the issue isn't something silly like memory usage growing due to lack of an autoreleasepool somewhere or something in a tight loop, like when unarchiving new updates and calculating sha256's of the archives in your archives directory.

I don't know if the issue here is with scanning updates (generating shas.. unarchiving the newest update is one-time cost) or generating deltas.

Taking a couple builds from your app here https://cog.losno.co/download that are around 8 days apart, and BinaryDelta on my machine seems to generate a diff pretty quickly with minimal memory usage, and the app isn't particularly big either. 

Also for a new update generate_appcast limits to just creating a max of 5 delta updates from previous versions (by default). So technically having other archives older than this (besides other releases which may have a different minimum OS requirement) isn't necessary.

**Comment by kode54** [comment] 2022-07-08 03:49
It reads all of them every time, then finishes like usual. I don't keep them locally for older OS versions, I directly link to the last update released for a given OS milestone. I don't prune them often because I'm lazy, is all.

**Comment by zorgiepoo** [comment] 2022-07-08 04:19
I'll think about automatically pruning items from the feed itself at least, otherwise we risk developers serving feeds that are larger than the (delta) updates themselves :). When I get the chance I'll try to replicate some sort of large corpus for investigating what bottlenecks there are.

**Comment by zorgiepoo** [comment] 2022-07-09 19:44
A couple of memory leaks are fixed in #2193.

**Closed** 2022-08-08 02:13 UTC
Labels: 1.x

**Comment by zorgiepoo** [comment] 2022-09-20 05:44
[generate_appcast in 2.3 beta](https://github.com/sparkle-project/Sparkle/releases) now automatically moves old updates aside into `old_updates` and tries to remove their respective cache files. There is also an `--auto-prune-update-files` option to automatically remove the files in `old_updates` after a while. Additionally `generate_appcast` will try to trim the generated appcast to a reasonable amount, removing items that should no longer be needed (only keeping the latest for each distinct branch point; e.g. updates with a different minimum system requirement). As such you should not end up generating a feed that is nearly 1 MB in size.

@kode54 you are welcome to test drive generate_appcast from the beta if you want.
