### ISSUE TITLE
Notarized copy doesn't work on computers, different from 

### ISSUE THREAD

**Issue by Voldemarus** [sparkle-project/Sparkle#1762] opened 2021-02-14 12:43 UTC
### Description of the problem

I try to distribute application with Sparkle framework, integrated via cocoapod (1.24.0) via notarisation service. 
All test are passed in Debug mode, zip file is uploaded to remote server, proper appcast file prepared and uploaded as well. 
SSL keys generated, all data in info.plist are correct. Check for update works.

Nut then I created **release** version **and notarized it**. It works on my local host, used to develop app as well. But as soon I send it to another user for testing, he got error message :

**...  can’t be updated if it’s running from the location it was downloaded to.**

Well, I built application on another computer, and notarized copy works well on that computer, but when I unpacked zip file on my first host, I got the same message. 

Any advice how to resolve this issue will be highly appreciated.

Regards,
Vladimir

Issue is reproduced on 10.15.7  and Bug Sur. 

### Do you use Sandboxing in your app?

Tried with both Sandbox On and Off - result is the same. Of course, hardened runtime is on, as required by notarization service. 

### Version of `Sparkle.framework` in the latest version of your app

1.24.0 - from cocoapods

XCode - Version 12.4

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)

N/A , just new app is created.

### Sparkle's output from Console.app
```
Nothing!!! No messages from Sparle are generated at all.
```

### Steps to reproduce the behavior

1. Build application with Sparjkle framework embedded
2. build and notarize application 
3. Zip notarized app
4. Send zip to another computer 
5. Unpack zip and run unpacked application 
6. Try to check for updates  (actually [[SUUpdater sharedUpdater] checkForUpdates:nil]; is used) IB-Version works in the same manner
7. You will get "is currently newest version.." if application is being run from the computer, used to build code, and "...can’t be updated if it’s running from..." if it is started from another Mac.

**Comment by michelf** [comment] 2021-02-14 13:06
Most likely this is due to [App Translocation](https://lapcatsoftware.com/articles/app-translocation.html) making the app read-only when running from its download location. Did you try moving it to the Application folder? It should work after moving it manually to somewhere else using the Finder.

**Comment by Voldemarus** [comment] 2021-02-14 13:22
Exactly, but the problem is that customer demands to run application and update it without moving :-( Is it possible to us temporary directory for downloading?  For example, in SPUDownloader.m replace PersistentDownloads to:

`-(NSString*)getAndCleanTempDirectory
{
//    NSString *rootPersistentDownloadCachePath = [[SPULocalCacheDirectory cachePathForBundleIdentifier:self.bundleIdentifier] stringByAppendingPathComponent:@"PersistentDownloads"];
//
//    [SPULocalCacheDirectory removeOldItemsInDirectory:rootPersistentDownloadCachePath];
//
//    NSString *tempDir = [SPULocalCacheDirectory createUniqueDirectoryInDirectory:rootPersistentDownloadCachePath];
    NSFileManager *fm = [NSFileManager defaultManager];
    NSURL *tempDirURL = [fm temporaryDirectory];
    NSString *tempDir = [tempDirURL.path stringByAppendingPathComponent:@"SPARKLE_DOWNLOAD"];
    // Now add application name as a cache for particular application
    NSString *bundleIdentifier = [[NSBundle mainBundle] bundleIdentifier];
    tempDir = [tempDir stringByAppendingPathComponent:bundleIdentifier];

    // Check for files inn this directory
    BOOL isDir = NO;
    BOOL isOk = NO;
    if ([fm fileExistsAtPath:tempDir isDirectory:&isDir]) {
        if (isDir) {
            // directory just exists - remove old content
            // but otiginal code doesn't perform any cleanup
            
        }
    } else {
        NSError *error = nil;
        [fm createDirectoryAtPath:tempDir withIntermediateDirectories:YES
                       attributes:nil error:&error];
        if (error) {
            // cannot create directory for update download
            [self.delegate downloaderDidFailWithError:error];
            [self cancel];
            return nil;
        }
    }

    if (!isOk) {
        // Okay, something's really broken with this user's file structure.
        NSError *error = [NSError errorWithDomain:SUSparkleErrorDomain code:SUTemporaryDirectoryError userInfo:@{ NSLocalizedDescriptionKey: [NSString stringWithFormat:@"Can't make a temporary directory for the update download at %@.", tempDir] }];
        
        [self.delegate downloaderDidFailWithError:error];
        
        [self cancel];
    }
    return tempDir;
}
`

**Comment by zorgiepoo** [comment] 2021-02-14 17:05
This is expected behavior from the OS unfortunately. Some developers choose to ask the user if they want to move the application to /Applications and have the app relaunch if it's running from a read-only mount(via LetsMove or similar) but Sparkle does not officially support doing this.

**Closed** 2021-09-06 19:10 UTC
Labels: 1.x
