### ISSUE TITLE
Threading issue with 1.19.0

### ISSUE THREAD

**Issue by saxmanbob** [sparkle-project/Sparkle#1247] opened 2018-06-08 10:40 UTC
Hi, I'm experiencing threading trouble when calling the SUUpdater method -(IBAction)checkForUpdates:sender;
I get my document window's windowDidBecomeMain method called on a secondary thread, when the Sparkle update checking panel disappears. This then breaks the rendering and auto layout associated with the document window and I get a stack trace and console warning message:

"This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes"

Am I doing something wrong or is this a known problem? I notice there's a mention of threading in the release notes: 
"Changes to which methods run on the main thread. Note: some delegate methods may be called on non-main thread now. (Kornel)"

I don't get this problem when Sparkle checks for updates automatically, after the app starts.

**Comment by saxmanbob** [comment] 2018-06-08 11:11
FYI, I upgraded to 1.19.0 after running into this problem on MacOS 10.13:
https://stackoverflow.com/questions/46088843/macos-10-13-scheduling-the-nsurldownload-loader-is-no-longer-supported

**Comment by saxmanbob** [comment] 2018-06-08 11:35
I've just downgraded to 1.18.1 and the threading problem isn't there. 
The NSURLDownload problem is though.

**Comment by jkbullard** [comment] 2018-06-08 11:58
@saxmanbob - This may be the same as #1236, which was fixed in a18282ec79e32812d8d050ddae664052ec81de25 but isn't in a release yet.

**Comment by saxmanbob** [comment] 2018-06-08 13:09
@jkbullard Ah yes, looks like it. Thanks for the heads up. I'll keep an eye on the releases.

**Comment by core-code** [comment] 2018-11-11 20:03
i may also be seeing this in 1.20:

```

Thread 5 Crashed:: Dispatch queue: NSOperationQueue 0x6000004bf1c0 (QOS: UNSPECIFIED)
0   com.apple.WebCore             	0x00007fff4006f63d WebCore::TimerBase::setNextFireTime(WTF::MonotonicTime) + 365
1   com.apple.WebCore             	0x00007fff3fff48fd WebCore::PerformanceMonitor::activityStateChanged(unsigned int, unsigned int) + 173
2   com.apple.CoreFoundation      	0x00007fff31e83306 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
3   com.apple.CoreFoundation      	0x00007fff31e83280 ___CFXRegistrationPost_block_invoke + 63
4   com.apple.CoreFoundation      	0x00007fff31e831a1 _CFXRegistrationPost + 398
5   com.apple.CoreFoundation      	0x00007fff31e8b5ed ___CFXNotificationPost_block_invoke + 87
6   com.apple.CoreFoundation      	0x00007fff31df213a -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1633
7   com.apple.CoreFoundation      	0x00007fff31df14fd _CFXNotificationPost + 742
8   com.apple.Foundation          	0x00007fff34173bab -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
9   com.apple.AppKit              	0x00007fff2f5a5f06 -[NSWindow becomeKeyWindow] + 1428
10  com.apple.AppKit              	0x00007fff2f4c8a12 -[NSWindow _changeKeyAndMainLimitedOK:] + 878
11  com.apple.AppKit              	0x00007fff2f612bdc -[NSWindow _orderOutAndCalcKeyWithCounter:stillVisible:docWindow:] + 1249
12  com.apple.AppKit              	0x00007fff2f3ae172 NSPerformVisuallyAtomicChange + 132
13  com.apple.AppKit              	0x00007fff2f526ee3 -[NSWindow _doWindowOrderOutWithWithKeyCalc:forCounter:orderingDone:docWindow:] + 80
14  com.apple.AppKit              	0x00007fff2f526936 -[NSWindow _reallyDoOrderWindowOutRelativeTo:findKey:forCounter:force:isModal:] + 435
15  com.apple.AppKit              	0x00007fff2f4cab90 -[NSWindow _reallyDoOrderWindow:relativeTo:findKey:forCounter:force:isModal:] + 172
16  com.apple.AppKit              	0x00007fff2f4c974f -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:] + 283
17  com.apple.AppKit              	0x00007fff2f4c95d2 -[NSWindow orderWindow:relativeTo:] + 152
18  com.apple.AppKit              	0x00007fff2fc8b99d -[NSWindow _finishClosingWindow] + 461
19  com.apple.AppKit              	0x00007fff2f6fac64 -[NSWindow _close] + 364
20  org.sparkle-project.Sparkle   	0x00000001059cdd57 -[SUUserInitiatedUpdateDriver closeCheckingWindow] + 122
21  org.sparkle-project.Sparkle   	0x00000001059ce1fe -[SUUserInitiatedUpdateDriver appcastDidFinishLoading:] + 80
22  org.sparkle-project.Sparkle   	0x00000001059a0ee1 -[SUAppcast downloaderDidFinishWithTemporaryDownloadData:] + 181
23  org.sparkle-project.Sparkle   	0x00000001059ba71f -[SPUDownloader downloadDidFinishWithData:] + 124
24  org.sparkle-project.Sparkle   	0x00000001059aea06 -[SPUDownloaderSession downloadDidFinish] + 440
25  org.sparkle-project.Sparkle   	0x00000001059ae271 -[SPUDownloaderSession URLSession:downloadTask:didFinishDownloadingToURL:] + 140
26  com.apple.CFNetwork           	0x00007fff30eddd9f __82-[NSURLSession delegate_downloadTask:didFinishDownloadingToURL:completionHandler:]_block_invoke + 38
27  com.apple.Foundation          	0x00007fff341b8a47 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
28  com.apple.Foundation          	0x00007fff341b894e -[NSBlockOperation main] + 68
29  com.apple.Foundation          	0x00007fff3418df7a -[__NSOperationInternal _start:] + 686
30  com.apple.Foundation          	0x00007fff341b867f __NSOQSchedule_f + 227
31  libdispatch.dylib             	0x00007fff5ee63d4f _dispatch_call_block_and_release + 12
32  libdispatch.dylib             	0x00007fff5ee64dcb _dispatch_client_callout + 8
33  libdispatch.dylib             	0x00007fff5ee675d8 _dispatch_continuation_pop + 427
34  libdispatch.dylib             	0x00007fff5ee66c7a _dispatch_async_redirect_invoke + 718
35  libdispatch.dylib             	0x00007fff5ee72d1a _dispatch_root_queue_drain + 325
36  libdispatch.dylib             	0x00007fff5ee734b1 _dispatch_worker_thread2 + 90
37  libsystem_pthread.dylib       	0x00007fff5f0a46ee _pthread_wqthread + 619
38  libsystem_pthread.dylib       	0x00007fff5f0a4415 start_wqthread + 13
```

**Comment by kornelski** [comment] 2018-11-11 20:11
This is fixed in #1216

**Closed by kornelski** 2018-11-11 20:11 UTC

**Comment by core-code** [comment] 2018-11-11 20:13
is there an actual stable release where this is fixed or do we need to wait until 1.21?

**Comment by kornelski** [comment] 2018-11-11 20:30
It's in 1.21. Please try it.

**Comment by core-code** [comment] 2018-11-11 20:31
sorry i can't. i can't reproduce the crash myself, it was just reported by a user. and i can't deploy alpha releases in the product.
