### ISSUE TITLE
Shipping pre-release builds of Sparkle 2.x via Swift Package Manager

### ISSUE THREAD

**Issue by tonyarnold** [sparkle-project/Sparkle#1883] opened 2021-07-05 06:54 UTC
It would be great to do away with some of the tooling that I'm currently maintaining for my projects by making pre-release builds of Sparkle 2.x available via Swift Package Manager (SPM). 

- I understand that the project is currently shipping Sparkle 1.x builds via SPM.
- I also understand that Sparkle 2.0 is _not_ ready to ship yet, and there are ongoing discussions about the API surface that affect any potential ETA. 

Still, it would be great if we could automate deployment of 2.x binary builds for SPM, and commit to tagging some early version of the branch as a pre-release. 

As always, I'm happy to help where I can and commit my time/efforts to this issue.

**Comment by zorgiepoo** [comment] 2021-07-05 19:25
Yeah we should figure out how to make prereleases for SPM and I think it's a good time to start doing that. Just haven't looked into it yet so feel free making PRs needed to do this.

cc @thebluepotato

**Comment by tonyarnold** [comment] 2021-07-05 23:30
Actually, is it even possible to ship the XPC Services via SPM? (Even as binaries)

**Comment by zorgiepoo** [comment] 2021-07-05 23:37
It might be possible, see https://github.com/sparkle-project/Sparkle/pull/1635#issuecomment-690288772

**Comment by tonyarnold** [comment] 2021-07-05 23:42
So it sounds like most of the hard work is done - I'd need to automate the release to GitHub via Actions to solve the immediate issue?

**Comment by zorgiepoo** [comment] 2021-07-06 08:11
I think... all we need to do is make a new tag `2.0.0-rc1`, run `make release`, push Package.swift / tag changes, and potentially add a pre-release draft / changelog on GitHub.

**Comment by tonyarnold** [comment] 2021-07-12 01:17
Excellent! So how's about an early alpha release of 2.0.0 to test that it's all working? I understand the API is still in flux for v2, but it'd be great to pick a point and start doing pre-releases.

**Comment by zorgiepoo** [comment] 2021-07-14 08:09
There are some recent DSA (potentially Apple Code Signing only too) deprecation / migration changes merged in 2.x that may be important enough to back port to 1.x and even make a small release there first (without having to think about if ordering will matter when tagging releases..)

There's also some documentation changes I'm working on, and some migration changes I should note for people migrating from earlier 2.x versions when creating a prerelease on GitHub.

Currently I don't have more API plans other than extending / taking a look at generate_appcast, but you never know..

**Comment by tonyarnold** [comment] 2021-07-14 23:35
> without having to think about if ordering will matter when tagging releases

I think that as long as you mark the 2.x series as pre-releases (via the checkbox on the Release page), then it won't interfere with the flow of tools like SPM. 

> There's also some documentation changes I'm working on […]

How can I help? I'm not here to just drop tasks on your lap and make demands of your time, I'm happy to contribute, too 😄

**Comment by kornelski** [comment] 2021-07-15 14:43
I thought SPM uses the git (the real git protocol), not GitHub proprietary API? Pre-release tag doesn't exist in git as a concept.

**Comment by zorgiepoo** [comment] 2021-07-15 15:22
Some low hanging fruit is adding SPM button to sparkle homepage in the website repo and explaining how tools can be found by right clicking / showing package contents of the package I think? Also verifying that it's safe/good on upgrades to reference files in the package. They're stored somewhere in DerivedData. That would be important for XPC Services.

Contemplating what to deprecate for both 1.x/2.x (#1892)

I think both SPM and Cocoapods use convention of `x.j.z[-prereleaseIdentifier]` as the tag format, or something like that.

**Comment by tonyarnold** [comment] 2021-07-19 01:25
> I thought SPM uses git tags (the real git protocol), not GitHub proprietary API? Pre-release tag doesn't exist in git as a concept.

You're absolutely right. Sorry, I was confused by all of the moving parts here, despite shipping everything I work on via GitHub releases right now 😭

**Comment by zorgiepoo** [comment] 2021-07-23 06:34
We can start committing a `2.0.0-beta.1` tag whenever. I don't think changing the bundle version from `2.0.0` is necessary.

I think the process is add an (annotated?) tag, run `make release`, push the tag, upload the assets.

There is one binary delta issue I'm looking into for 1.27, but we can just spin another 2.0.0 beta release at any point.

**Comment by kornelski** [comment] 2021-07-23 11:51
Would it be possible to make builds with GitHub Actions?

For Sparkle 1.x I just did a local build, but that's manual and not reproducible.

**Comment by zorgiepoo** [comment] 2021-07-24 01:24
I guess but we don't have the pipeline set up for that, anyone can volunteer =)

Requirements probably are:
* Can't trust GitHub action's zip tool. I.e, we should use ditto for creating SPM zip archive. (they have issues with making zips for macOS bundles using their infrastructure and not native tools.. long short story short, zip is a bad unreliable format)
* Create an event that uploads the distribution files.. At worst case we have to download the files and manually extract/upload them, at best case, we can draft a prerelease from there automatically which would involve some sort of auth token/secret probably.

Presently we don't upload SPM archive as an artifact due to usage of zip tool and due to saving space.

Anyway, for now, I can make a local build and we can create the tag and changelog if you're OK with that.

**Comment by thebluepotato** [comment] 2021-08-25 09:44
Finally found the time to reply. For some of the questions raise: as far as XPC are "just" bundled with the 2.x Cocoapods releases, they are also merely bundled within the zip file. For the tag, indeed it uses standard git tags with the crucial requirement that they follow SemVer conventions. AFAIK the scripts called during `make release` check that the tag is correct. In short: if you want to publish a pre-release package ready for SPM, you just have to commit, tag a prerelease version and run `make release`. The scripts take care of creating the appropriate archives, zip them, update Package.swift and shift the tag by one commit. The only manual part is not forgetting to upload the resulting zip as part of the release assets on GitHub. I think that's the main thing to be automated with Actions.

**Comment by zorgiepoo** [comment] 2021-08-29 03:55
I created a pre-release for 2.x. Barring some minor issues, this is being done now.

The XPC Services do get bundled in the SPM distribution.. but, it's unknown to me if they will be awkward to reference from a project as they're in some derived data location. If there's issues there, they probably need to be filed to Apple/Xcode.

**Comment by tonyarnold** [comment] 2021-09-15 00:21
Has anyone successfully integrated Sparkle 2.0.0-beta.X into their project via SwiftPM? 

I'm seeing build cycles with Xcode 13.0RC. These could be related to my project setup, but I'm keen to hear if anyone else has made this work? 

I reference `$(TARGET_BUILD_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Sparkle.framework` within a few of my build phases to do things like re-codesign, and remove Sparkle from Mac App Store builds.

**Comment by 1024jp** [comment] 2021-09-15 00:35
@tonyarnold Hi, I already succeeded in bundling sandboxed Sparkle via SwiftPM.
The latest version of my app was released using it even with notarization.

A tricky part for me was referring XPCs from the project.
Currently, I use "Relative to Build Products" and a relative path like `./../../SourcePackages/artifacts/Sparkle/XPCServices/org.sparkle-project.InstallerLauncher.xpc`.
It works when I build &M run the app locally, but for a release build (more exactly, archiving it for Apple's notarization), I need to change the path from the relative one to the absolute path every times.
So, if anyone knows more better way, I'd like to hear. 

For details, see my [project](https://github.com/coteditor/CotEditor).

**Comment by gpoitch** [comment] 2021-09-15 01:04
Working well for me with SwiftPM.
Needed to copy InstallerLauncher.xpc from source into the project so it's signed correctly. Haven't attempted to strip it + resign the framework and instead just taking the additonal size hit for now.

**Comment by neiljhaveri** [comment] 2021-09-21 18:41
I ran into the same issue as @1024jp trying to reference InstallerLauncher.xpc from artifacts – using a path that is "relative to build products" doesn't work for archive builds. If there are recommendations on how to reference the XPC service besides having to just copy it in, I'd love to hear!

**Comment by zorgiepoo** [comment] 2021-09-22 05:59
I don't know. From @1024jp's analysis it doesn't sound like Xcode has a good way of referencing additional artifacts in a project like the XPC Services. And I don't think it is possible to just serve the XPC Services as swift packages. This would probably be worthy of a feedback report to Apple.

Unfortunately the XPC Services and the framework bundles do need to be aligned (the CFBundleVersion and CFBundleShortVersionString values will match when they're aligned), so if the framework updates, the XPC Services need to update too, if you go with the route of just copying them.

Maybe one hack is having an automated script that copies the XPC Services to your project and updates the XPC Services automatically when they become un-aligned with the framework used..

CocoaPods actually does this better I think and makes the XPC Services easy to reference.

**Comment by zorgiepoo** [comment] 2021-09-22 06:04
Re-opening for sake of seeking and documenting a working workflow (if possible)

**Comment by zorgiepoo** [comment] 2021-09-23 02:23
The more that I think about this, I think I should re-evaluate bundling the installer launcher and downloader XPC Services inside the framework (still making them optional / opt-in). It has been several years since I've last tried doing it that way.

**Comment by zorgiepoo** [comment] 2021-09-25 06:39
> The more that I think about this, I think I should re-evaluate bundling the installer launcher and downloader XPC Services inside the framework (still making them optional / opt-in). It has been several years since I've last tried doing it that way.

Unfortunately after trying this, XPC Services inside a framework in an app bundle don't get recognized (or I can't get this to work / find the service name), so this is probably not an option.

**Closed** 2021-10-18 06:35 UTC

**Comment by neiljhaveri** [comment] 2021-11-04 22:10
I adopted this in my sandboxed app today, and it was a super-smooth experience! Thanks again for making this happen, @zorgiepoo!

**Comment by billymeltdown** [comment] 2021-11-05 16:01
@zorgiepoo I've also got beta 4 running well in our app (sandboxed), everything working as expected!

I should also add that earlier in the year (I think pre-April 14th changes to XPC services) I switched us from 1.x to 2.x, and the documentation, plus the subsequent updates and changes, has been really easy to follow.
