### ISSUE TITLE
1.20 missing NIBs in all language folders except ar.lproj

### ISSUE THREAD

**Issue by XericDesign** [sparkle-project/Sparkle#1271] opened 2018-07-22 23:48 UTC
ar.lproj contains:

SUAutomaticUpdateAlert.nib
SUUpdateAlert.nib
SUUpdatePermissionPrompt.nib

but none of the other language folders contain these files. This results in errors when an update is available as it can't open an English (or many other) NIB.

**Comment by kornelski** [comment] 2018-07-24 20:05
Duplicate of #1271

**Closed by kornelski** 2018-07-24 20:05 UTC
