### ISSUE TITLE
Sparkle update release notes are not adapted to Dark Mode

### ISSUE THREAD

**Issue by MajuMadhusudanan** [sparkle-project/Sparkle#1714] opened 2021-01-06 07:08 UTC
Hi,

Sparkle update release notes are not adapted to Dark Mode. Release notes is not visible in software update dialog. During this time macOS is in dark mode, This works fine in light mode.

how do i show release notes properly in dark mode ?

**Comment by kornelski** [comment] 2021-01-06 14:39
We have support for dark mode. Are you using the latest version of Sparkle?

**Comment by MajuMadhusudanan** [comment] 2021-01-06 15:25
> We have support for dark mode. Are you using the latest version of Sparkle?

Yes. I believe its 1.24. I have added sparkle framework as a dependency via Xcode --> Swift packages -> Add Package Dependency.

**Comment by kornelski** [comment] 2021-01-06 18:04
Oh, that's unexpected. I've merged webview refactoring, so hopefully the next version will behave better.

**Comment by MajuMadhusudanan** [comment] 2021-01-07 00:46
when is next release ?

**Comment by zorgiepoo** [comment] 2021-01-07 03:33
Might help if you post a screenshot. Sparkle applies a default .css scheme for dark mode, might need to check that and your current html / css. Things have been redone in tip of branch but color schemes shouldn’t have changed in theory.

**Comment by MajuMadhusudanan** [comment] 2021-01-07 05:53
> Might help if you post a screenshot. Sparkle applies a default .css scheme for dark mode, might need to check that and your current html / css. Things have been redone in tip of branch but color schemes shouldn’t have changed in theory.

<img width="619" alt="software update" src="https://user-images.githubusercontent.com/23079368/103856461-b1bd5500-50da-11eb-9d34-29e3bc8d5d26.png">

**Comment by MajuMadhusudanan** [comment] 2021-01-07 05:53
> > Might help if you post a screenshot. Sparkle applies a default .css scheme for dark mode, might need to check that and your current html / css. Things have been redone in tip of branch but color schemes shouldn’t have changed in theory.
> 
> <img alt="software update" width="619" src="https://user-images.githubusercontent.com/23079368/103856461-b1bd5500-50da-11eb-9d34-29e3bc8d5d26.png">

You can find the attached screenshot. Release notes is not visible properly now on dark mode

**Comment by kornelski** [comment] 2021-01-07 21:26
The release notes have a black background, which is what we expect when we mean support for dark mode. I'm guessing the problem here is that you get black-on-black text? But you've masked out some text at top of release notes, so something must have been shown. Are you sure it's not caused by your CSS?

**Comment by MajuMadhusudanan** [comment] 2021-01-12 23:48
> The release notes have a black background, which is what we expect when we mean support for dark mode. I'm guessing the problem here is that you get black-on-black text? But you've masked out some text at top of release notes, so something must have been shown. Are you sure it's not caused by your CSS?

This is our issue only. we have fixed it. Thanks

**Closed** 2021-01-13 11:00 UTC
Labels: 1.x
