### ISSUE TITLE
Xcode 7.1 error: include of non-modular header inside framework module

### ISSUE THREAD

**Issue by kujenga** [sparkle-project/Sparkle#675] opened 2015-11-04 04:01 UTC
I have a Swift based application that is updated using Sparkle. I also use Cocoapods to manage my dependencies, including Sparkle. I just got around to updating my version of Xcode to the latest 7.1, and after doing so my application now fails to build. I get the following errors in Sparkle.h

<img width="768" alt="screen shot 2015-11-03 at 10 50 18 pm" src="https://cloud.githubusercontent.com/assets/4854867/10929106/4b9f38e6-827d-11e5-932b-170002dea395.png">

I was able to fix this by modifying those imports to the following:

```objc
#import "SUAppcast.h"
#import "SUAppcastItem.h"
#import "SUStandardVersionComparator.h"
#import "SUUpdater.h"
#import "SUVersionComparisonProtocol.h"
#import "SUVersionDisplayProtocol.h"
#import "SUErrors.h"
```

If the fix is as simple as making that change, I'm happy to whip up a PR for it, but if there are issues with compatibility for non-Swift apps or previous versions of Xcode, there might need to be more mechanics involved.

**Comment by jakepetroules** [comment] 2015-11-04 04:53
Duplicate of #668

**Closed by jakepetroules** 2015-11-04 04:53 UTC
