### ISSUE TITLE
buggy multi-language system

### ISSUE THREAD

**Issue by wxiaoguang** [sparkle-project/Sparkle#652] opened 2015-10-08 11:50 UTC
It seems that only English xib/strings are correct.

Other languages often have problems:
1. bad outlet references (eg: bad "description/descriptionField" references in SUUpdateAlert.xib) 
2. incorrect translations & out-dated translations

cocoa's multi-language processor with xib is really valueless. I think using NSLocalizedString to load translations from string files is a good choice for Sparkle, and the translations should be easy to be updated.

**Comment by tualatrix** [comment] 2015-11-12 05:59
+1

Sparkle should update to use Base Internationalization.

**Comment by jakepetroules** [comment] 2015-11-12 08:23
That requires 10.8, which is higher than our current minimum.

**Comment by pornel** [comment] 2015-11-12 11:57
Please test #681

**Comment by pornel** [comment] 2015-11-12 14:01
This should be fixed by #681. Please test version from master.

**Comment by zorgiepoo** [comment] 2015-11-12 22:31
The issue I had reproduced in #672 I can't reproduce anymore, after this change.

By the way, why do we have nibs for different languages (and why do some language folders not have nibs)? Shouldn't Auto Layout and different string files suffice, or is this related to Base Internationalization? In any case, we may want to consider on when we will want to drop 10.7; it has been enjoying its long stay.

**Comment by MaddTheSane** [comment] 2015-11-12 23:32
Re: .strings files.
Having separate strings files for each nib does require the use of base localizations. Base localization requires targeting 10.8 (IIRC). I have an old branch that migrates to base localization and moves to .strings, but it's been awhile since I updated it.

**Comment by wxiaoguang** [comment] 2015-11-13 04:23
I didn't mean to use "Base localization", but to load & set localized strings to UI manually. You just need only one (or two for right-left text) NIB file.

ps: I don't like "Base localization" either because its dirty "id" mechanism

**Comment by zorgiepoo** [comment] 2015-11-13 15:48
> I didn't mean to use "Base localization", but to load & set localized strings to UI manually. You just need only one (or two for right-left text) NIB file.

Yeah, my past experience is that letting Xcode generate strings for nib files has been a bad one with the wonky id's it generates. Setting the strings in code does sound better.

I'm still puzzled why fi.lproj folder has no xib files in the repo, but fr.lproj on the other hand does, though.

**Comment by pornel** [comment] 2015-11-13 18:40
I've been using Base localisation in ImageOptim and it works reasonably well. Xcode stopped generating painfully-conflicting numeric identifiers, and uses pretty stable UUID-like ones now, which is manageable.

If we were to support both 10.7 and a single XIB updated from strings, we'd essentially re-implement Base localisation. I'm not sure if it's worth it.

**Comment by kainjow** [comment] 2015-11-13 18:51
Could also switch to generating UI dynamically through autolayout's visual format language and drop nibs altogether.

**Comment by zorgiepoo** [comment] 2015-12-15 02:12
@pornel To satisfy my curiosity do you know why some language folders do not have xib files currently?

**Comment by pornel** [comment] 2015-12-15 09:42
@zorgiepoo it is a mystery to me too (bug)

**Comment by pornel** [comment] 2015-12-15 13:50
@zorgiepoo I've checked. The reason is that the strings files are old and incomplete (probably for a very old version of Sparkle).

**Comment by pornel** [comment] 2016-12-28 22:20
I think we're OK with our current xibs, given that we support 10.7.

**Closed by pornel** 2016-12-28 22:20 UTC
