### ISSUE TITLE
App quits but doesn't install or re-launch

### ISSUE THREAD

**Issue by brendand** [sparkle-project/Sparkle#1067] opened 2017-04-24 21:16 UTC
I'm using the ui-separation-and-xpc branch of Sparkle and I believe I have everything setup and signed properly. I get as far as downloading the update and the Install and Relaunch alert is displayed, but when I press that, my app quits but the new version doesn't get installed or launched. It's still hiding away in the `~/Caches/...../org.sparkle-project.Sparkle/Installation/...../` folder(s).

The only messages I see in Console that appear at this time are the following:

```
default	15:07:31.061479 -0600	Autoupdate	Extracting using '/usr/bin/ditto' '-x' '-k' '-' < '/Users/brendan/Library/Caches/com.tapzapp.tapforms-mac/org.sparkle-project.Sparkle/Installation/WmYUQk0Sw/TapFormsMac5.app.zip' '/Users/brendan/Library/Caches/com.tapzapp.tapforms-mac/org.sparkle-project.Sparkle/Installation/WmYUQk0Sw'
default	15:07:31.924368 -0600	Autoupdate	UNIX error exception: 17
default	15:07:31.924687 -0600	Autoupdate	0x7ffef35267b0 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
default	15:07:31.926152 -0600	Autoupdate	UNIX error exception: 17
default	15:07:31.927523 -0600	Autoupdate	CSSM Exception: -2147415792 CSSMERR_CSP_INVALID_KEY
default	15:07:31.928082 -0600	Autoupdate	UNIX error exception: 17
default	15:07:31.928194 -0600	Autoupdate	UNIX error exception: 17
default	15:07:31.965213 -0600	Autoupdate	UNIX error exception: 17
default	15:07:31.982304 -0600	Autoupdate	UNIX error exception: 17
default	15:07:33.034705 -0600	Tap Forms Mac 5	TIC TCP Conn Event [3:0x610000381a00]: 2 Err(0)
default	15:07:33.034809 -0600	Tap Forms Mac 5	TIC TCP Conn Cancel [3:0x610000381a00]
default	15:07:33.034965 -0600	Tap Forms Mac 5	TIC TCP Conn Destroyed [3:0x610000381a00]
default	15:07:49.229986 -0600	kernel	[Tap Forms Mac 5 pid 39568 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:53.211
```

I suspect it's perhaps a problem due to that `UNIX error exception: 17` message that keeps appearing at this time, but I don't know what that means and I haven't found much information on it.

You can see after the app exits, nothing else happens. The app is simply quit.

Along with the `Sparkle.framework`, I also have the following files in my `XPCService` folder within my app's bundle:

```
org.sparkle-project.InstallerConnection.xpc
org.sparkle-project.InstallerLauncher.xpc
org.sparkle-project.InstallerStatus.xpc
```

I've removed the Autoupdate and Updater apps from the `Sparkle.framework` as was suggested because they also exist in the .xpc. 

I feel like I'm so very close to getting this working now.

My app is both Developer ID signed and sandboxed. I'm using macOS Sierra 10.12.4 for development and testing. But my app also runs on El Capitan.

**Comment by pornel** [comment] 2017-04-24 23:21
Previous issue mentioning this error was about codesigning problem:  #1031

**Comment by brendand** [comment] 2017-04-24 23:34
When I execute the `sign_update` command, all that happens is it dumps out the digest value for the zip file. It doesn't seem to update the zip file itself by signing it. At least I don't see the modification date set on the .zip file. Could it be that my zip file isn't being signed? But it doesn't seem to have a problem extracting the files from it and putting it into the Caches folder. It just doesn't do anything with it after that.

I'm pretty sure my app is code signed properly. RB App Checker seems to suggest everything is signed, including the Autoupdate and Updater apps, with my Developer ID.

I'll try sticking a bunch of `SULog` in a bunch of places.

**Comment by brendand** [comment] 2017-04-24 23:39
And when I execute `codesign --deep --verify -vvv ./Tap\ Forms\ Mac\ 5.app` I get:

```
./Tap Forms Mac 5.app: valid on disk
./Tap Forms Mac 5.app: satisfies its Designated Requirement
```

So I'm pretty sure I'm code signed properly.

**Comment by brendand** [comment] 2017-04-25 00:42
I added a bunch of log messages to a bunch of the Autoupdate classes. This is what I have so far:

```
default	18:40:25.220895 -0600	kernel	[Tap Forms Mac 5 pid 52583 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:37.343
default	18:40:25.244779 -0600	Autoupdate	noteExitKQueueCallback
default	18:40:25.245166 -0600	Autoupdate	invokeCompletionWithSuccess: 1
default	18:40:25.245305 -0600	Autoupdate	finishInstallationAfterHostTermination
default	18:40:25.245607 -0600	Autoupdate	shouldShowUI: 1
default	18:40:25.245656 -0600	Autoupdate	performStage2InstallationIfNeeded
default	18:40:25.245934 -0600	Autoupdate	finishInstallationAfterHostTermination installationPath: /Users/brendan/Desktop/Tap Forms Direct 2017-04-24 18-39-33/Tap Forms Mac 5.app
default	18:40:25.246019 -0600	Autoupdate	performFinalInstallationProgressBlock: error: (null)
default	18:40:25.246278 -0600	Autoupdate	startInstallationToURL: file:///Users/brendan/Desktop/Tap%20Forms%20Direct%202017-04-24%2018-39-33/Tap%20Forms%20Mac%205.app/, newURL: file:///Users/brendan/Library/Caches/com.tapzapp.tapforms-mac/org.sparkle-project.Sparkle/Installation/GHddGBLlg/Tap%20Forms%20Mac%205.app/
default	18:40:25.246321 -0600	Autoupdate	progress: 1/10
```

So the last thing that executed was this in the `SUPlainInstaller.m` file.

```
    SULog(SULogLevelDefault, @"progress: 1/10");
    progress(1/10.0);
```

I put a log statement after `progress(1/10.0);` and it never reached it. So it seems to be stopping at `progress()`.

**Comment by pornel** [comment] 2017-04-25 00:51
Oh, that's an odd one! But it's a new addition, so it may actually be the cause. I'll check it tomorrow.

**Comment by brendand** [comment] 2017-04-25 01:03
Ok, so I did one last test. I commented out all of the calls to `progress()` but I left in all the comments where `progress()` would have been called.

Success!

My app was exited, updated, and it relaunched.

```
default	19:01:17.306526 -0600	kernel	[Tap Forms Mac 5 pid 55518 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:25.274
default	19:01:17.333722 -0600	Autoupdate	noteExitKQueueCallback
default	19:01:17.334319 -0600	Autoupdate	invokeCompletionWithSuccess: 1
default	19:01:17.334721 -0600	Autoupdate	finishInstallationAfterHostTermination
default	19:01:17.335124 -0600	Autoupdate	shouldShowUI: 1
default	19:01:17.335585 -0600	Autoupdate	performStage2InstallationIfNeeded
default	19:01:17.336892 -0600	Autoupdate	finishInstallationAfterHostTermination installationPath: /Users/brendan/Desktop/Tap Forms Direct 2017-04-24 19-00-31/Tap Forms Mac 5.app
default	19:01:17.337574 -0600	Autoupdate	performFinalInstallationProgressBlock: error: (null)
default	19:01:17.338867 -0600	Autoupdate	startInstallationToURL: file:///Users/brendan/Desktop/Tap%20Forms%20Direct%202017-04-24%2019-00-31/Tap%20Forms%20Mac%205.app/, newURL: file:///Users/brendan/Library/Caches/com.tapzapp.tapforms-mac/org.sparkle-project.Sparkle/Installation/fVhg7d5gL/Tap%20Forms%20Mac%205.app/
default	19:01:17.339408 -0600	Autoupdate	progress: 1/10
default	19:01:17.339723 -0600	Autoupdate	after progress: 1/10
default	19:01:17.461742 -0600	Autoupdate	after updateAccessTimeOfItemAtRootURL
default	19:01:17.463329 -0600	Autoupdate	progress: 2/10
default	19:01:17.464113 -0600	Autoupdate	progress: 3/10
default	19:01:17.475396 -0600	Autoupdate	progress: 4/10
default	19:01:17.475636 -0600	Autoupdate	progress: 5/10
default	19:01:17.475753 -0600	Autoupdate	progress: 6/10
default	19:01:17.476021 -0600	Autoupdate	progress: 7/10
default	19:01:17.476961 -0600	Autoupdate	progress: 8/10
default	19:01:17.477330 -0600	Autoupdate	progress: 9/10
default	19:01:17.646136 -0600	Autoupdate	progress: 10/10
default	19:01:17.646186 -0600	Autoupdate	performStage3Installation
default	19:01:17.646325 -0600	Autoupdate	self.shouldRelaunch: 1
default	19:01:17.646429 -0600	Autoupdate	pathToRelaunch: /Users/brendan/Desktop/Tap Forms Direct 2017-04-24 19-00-31/Tap Forms Mac 5.app
default	19:01:17.646550 -0600	Autoupdate	cleanupAndExitWithStatus: 0
```

**Comment by shusain93** [comment] 2017-05-04 23:40
I'm getting this issue too with my application, unsandboxed but with DeveloeprID. It runs and updates perfectly fine on my machine and a few others however for some users and one laptop (all on the latest Sierra) The update process begins and the "Install and relaunch" button closes and removes the app from the dock (but it does stay running!)

This is the relevant log data:
```
default	17:27:59.933027 -0600	MessageProxy	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	17:27:59.933138 -0600	MessageProxy	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	17:27:59.933221 -0600	MessageProxy	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	17:27:59.933555 -0600	MessageProxy	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	17:27:59.933646 -0600	MessageProxy	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	17:27:59.933743 -0600	MessageProxy	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	17:27:59.933826 -0600	MessageProxy	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	17:27:59.933922 -0600	MessageProxy	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	17:27:59.934008 -0600	MessageProxy	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	17:27:59.954601 -0600	MessageProxy	subsystem: com.apple.clouddocs, category: default, enable_level: 0, persist_level: 0, default_ttl: 14, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
default	17:28:00.208493 -0600	MessageProxy	<private> self <0x7f8db0992320> on thread <Main>
default	17:28:00.208672 -0600	MessageProxy	push: removePushObserver: removing self <private> uid <private> from center (null)
default	17:28:00.212305 -0600	MessageProxy	Deallocating CardDAVSource: <private>
default	17:28:00.321411 -0600	Autoupdate	subsystem: com.apple.SkyLight, category: default, enable_level: 0, persist_level: 0, default_ttl: 7, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
default	17:28:00.371061 -0600	Autoupdate	PID to listen: 19872

```

after PID to listen to the application hangs forever and must manually be relaunched. The update doesn't install correctly. The weird part is that this is machine dependent. If you'd like to try anything (or check out my code?) you can find [releases here](https://github.com/shusain93/OSXMessageProxy/releases) and the [general project here](https://github.com/shusain93/OSXMessageProxy). If I download version 1.1, from releases, unzip and move it, and then try to update I encounter this bug however when I replicate this exact behavior on my developer machine it updates perfectly fine.

**Comment by pornel** [comment] 2017-05-05 14:45
(Un)fortunately it updates fine on my machine too.

**Comment by shusain93** [comment] 2017-05-07 01:21
Okay I got it!

You need to remove `SUAutomaticallyUpdate` from your PLIST. If you have also used the NSUserDefaults method kill that too. After doing this my app updates just fine.

**Comment by pornel** [comment] 2017-06-28 23:51
I think this has been fixed in #1084

**Closed by pornel** 2017-06-28 23:51 UTC

**Comment by zeeshansuleman** [comment] 2021-01-07 07:50
i am having the same issue. Sparkle does not install and relaunch the update of my app.

**Comment by kornelski** [comment] 2021-01-07 21:23
The problem discussed in *this* issue has been fixed. Please don't add comments on closed issues. Go through troubleshooting steps and file a new bug if you find one.
