### ISSUE TITLE
'SUPipedUnarchiver' can go into infinite loop for some ZIP files, causing app to freeze.

### ISSUE THREAD

**Issue by core-code** [sparkle-project/Sparkle#1433] opened 2019-07-02 16:39 UTC
for easy reproduction i've taken the code from 'SUPipedUnarchiver' and embedded into a standalone app so you can quickly confirm this issue.

1.) download the attached "ZIPUncompresser" xcode project which uses SUPipedUnarchiver to uncompress ZIP files
2.) build and run the app using Xcode
3.) drag any ZIP file onto ZIPUncompresser, everything works fine
4.) download this zip file: https://updates.signal.org/desktop/signal-desktop-mac-1.25.3.zip
5.) drop it onto ZIPUncompresser
6.) SUPipedUnarchiver is stuck in an infinite loop in [archiveOutput writeData:data];

this problem will presumably send any app into a infinite loop that tries to update using ZIP files that are similar to 'signal-desktop-mac-1.25.3.zip'

bug happens on 10.14.5 and presumably other macOS versions

what is the rationale to use a pipe instead of directly pointing 'ditto' at the 'archivePath' anyway - which would presumably also be much faster?

**Comment by core-code** [comment] 2019-07-02 16:39
[ZIPUncompresser.zip](https://github.com/sparkle-project/Sparkle/files/3351064/ZIPUncompresser.zip)

**Comment by core-code** [comment] 2019-07-02 16:42
the underlying issue here is, of course, a macOS bug, -[NSFileHandle writeData:] can block forever. some good soul should report this to Apple.

**Comment by kornelski** [comment] 2019-07-02 21:45
Piping allows file to be read from host app's process, rather than ditto's process. It also avoids the need to serialize the path as an argument to the command. These things may not be critical, but to me piping seems like a preferred solution to communicate with subcommands.



As far as I understand, the problem is a deadlock, not really a loop (the tasks wait forever, not run forever).

**Comment by core-code** [comment] 2019-07-02 22:23
> Piping allows file to be read from host app's process, rather than ditto's process.

why is this better?

> It also avoids the need to serialize the path as an argument to the command. 

how is this in any way 'complicated'? the target path is already 'serialized' which is exactly zero work

> As far as I understand, the problem is a deadlock

yes, totally true, deadlock, not livelock, no looping involved


i solved the issue locally by creating a new 'SUUnpipedUnarchiver' just for ZIP files which doesn't use any piping.

**Comment by zorgiepoo** [comment] 2021-11-13 17:49
This is a badly constructed zip file (from a non-Sparkle based app). If you unarchive it on the system with Archive Utility today you'll see missing executable bits and broken symlinks. So this is a type of zip file that cannot be published today (ditto is able to manage with it though). Presumably the issue here is not all the contents of the zip file are needed, and so the task is done around the 103744442'th byte or so, but we are still trying to write data.

I would prefer not to use a pipe and just the archive file path.. but we use it to notify file progress. This would be nice to fix, but it's not a common issue.

**Comment by core-code** [comment] 2021-11-13 18:33
> This would be nice to fix, but it's not a common issue.

thanks there, i agree

**Comment by zorgiepoo** [comment] 2021-11-13 20:11
Still worthwhile not hanging, though.

**Comment by zorgiepoo** [comment] 2021-11-15 07:33
This will be fixed by #2023

**Closed** 2021-11-24 16:16 UTC
