### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by pornel** [sparkle-project/Sparkle#676] opened 2015-11-04 14:06 UTC
There's been a prerelease build out for a while now. Should we release it?

The current master contains a fix for install during shutdown, which I think is important (it may be the source of broken installs we hear about). Should we backport it to older release(s)?

There's a known bug with SMB mounts - https://github.com/sparkle-project/Sparkle/pull/657#issuecomment-150880093 Is it OK to release with it? Is that a regression?

**Comment by zorgiepoo** [comment] 2015-11-04 14:54
I also wanted to take a look at #672 and see if it's critical or not but haven't had chance to repoduce it yet.

**Comment by pornel** [comment] 2015-11-04 16:47
@zorgiepoo did SMB work in the previous release? i.e. is #657 a new fix for an old bug, or a fix for a regression introduced recently?

**Comment by zorgiepoo** [comment] 2015-11-05 02:53
Well the last time I tested that, Sparkle used to be able to update the app (well maybe not if it was binary-delta'ed) even though it ran into issues throughout the way (e.g, not being able to trash old app). I was testing by grabbing older versions of my app and trying to update on a mount. So it never completely worked, but this could be less working now -- on SMB mounts.

**Comment by zorgiepoo** [comment] 2015-11-05 03:17
I'm kind of unsure right now though and for some reason even when I replace the Sparkle framework in an app with a really old version of Sparkle, I get the feeling that the updater is still using a more updated version - kind of bizarre...

I agree about being weary of pulling that change though if we don't have to at the moment.

**Comment by zorgiepoo** [comment] 2015-11-08 20:39
Ok, I assume the issue I ran into was #571 when I was trying to test if updating worked with an old version of Sparkle, but it was using the downloaded one instead. I assume this is fixed now though?

**Comment by zorgiepoo** [comment] 2015-11-08 20:59
@pornel To answer your question my findings are that:

Sparkle 1.12: fails to update the app on SMB mount
Sparkle 1.11: can update app on SMB mount, but fails to trash the old app
Sparkle 1.10 or below: unreliable to test, since it may not obtain the correct sparkle bundle path for Autoupdate

**Comment by pornel** [comment] 2015-11-08 22:52
Thanks. So it's a regression. In that case I suggest we merge the fix and delay the next release, but in the meantime backport the shutdown fix as 1.11.1

**Comment by zorgiepoo** [comment] 2015-11-08 22:57
Well the regression and the "shut down" issue are tied to the same thing though: performing updates atomically, right?

We also try not to update if the system is shutting down event is received, but can't do anything if the user quits the app right before shutting off, so that doesn't solve much on its own.

**Comment by pornel** [comment] 2015-11-08 23:47
I've cherry-picked 66a11b83f0e6654f2ffc7c3d3792eb49f1b72e62 on top of 1.11.0, so that we can release stable 1.11.1 with that just fix.

**Comment by zorgiepoo** [comment] 2015-11-08 23:49
@pornel that doesn't really solve the issue though. It'll only reduce the chances slightly.

**Comment by pornel** [comment] 2015-11-08 23:49
It is far from perfect, but 1.11 is our stable version, and may be a better choice for those who prefer a version with known bugs over a version with unknown bugs :)

**Comment by pornel** [comment] 2015-11-09 00:59
https://github.com/sparkle-project/Sparkle/releases/tag/1.11.1
https://github.com/sparkle-project/Sparkle/releases/tag/1.12.0a3

**Comment by jakepetroules** [comment] 2015-11-09 02:15
:+1:

**Comment by pornel** [comment] 2015-12-14 19:25
Ready to release 1.12?

**Comment by jakepetroules** [comment] 2015-12-15 01:45
:+1:

**Comment by zorgiepoo** [comment] 2015-12-15 02:30
Not sure if you wanted to ponder about changing the bundle ID or not (#687) but I'm fine either way with what's decided.

**Comment by pornel** [comment] 2015-12-15 09:55
I'm not sure what consequences change of bundle ID would have, so I think it's better to address it in the next version.

**Comment by pornel** [comment] 2015-12-15 11:05
#696

**Closed** 2016-02-05 00:28 UTC
