### ISSUE TITLE
Vendor/ed25519/* missing from source code packages

### ISSUE THREAD

**Issue by pierswalter** [sparkle-project/Sparkle#1681] opened 2020-11-22 19:13 UTC
Both source code packages do not contain the files in Vendor/ed25519/, hence compilation from source fails

(https://github.com/sparkle-project/Sparkle/archive/1.24.0.zip, https://github.com/sparkle-project/Sparkle/archive/1.24.0.tar.gz)

**Comment by fedeci** [comment] 2020-11-22 19:19
Duplicate of #1678

**Closed** 2020-11-22 20:11 UTC
Labels: 1.x
