### ISSUE TITLE
Update fails on first attempt, succeed on 2nd

### ISSUE THREAD

**Issue by cherpake** [sparkle-project/Sparkle#1079] opened 2017-05-22 10:58 UTC
I'm getting this in the console.

```
Succeeded authorizing right 'system.privilege.admin' by client '/Users/cherpake/Library/Caches/com.cherpake.macrc.server/org.sparkle-project.Sparkle/Autoupdate.app' [37325] for authorization created by '/Users/cherpake/Library/Caches/com.cherpake.macrc.server/org.sparkle-project.Sparkle/Autoupdate.app' [37325] (13,0)

Failed to perform final installation Error: Error Domain=SUSparkleErrorDomain Code=4005 "Failed to execute package installer." UserInfo={NSLocalizedDescription=Failed to execute package installer., NSUnderlyingError=0x7faa14605620 {Error Domain=SUSparkleErrorDomain Code=4001 "Failed to run authorization tool /Users/cherpake/Library/Caches/com.cherpake.macrc.server/org.sparkle-project.Sparkle/Autoupdate.app/Contents/MacOS/fileop (-60008)." UserInfo={NSLocalizedDescription=Failed to run authorization tool /Users/cherpake/Library/Caches/com.cherpake.macrc.server/org.sparkle-project.Sparkle/Autoupdate.app/Contents/MacOS/fileop (-60008).}}}
```

**Comment by 1024jp** [comment] 2017-05-22 11:57
That's right. I should start thinking about this...

**Comment by jezrielbajan** [comment] 2017-05-26 09:01
I am having the same issue. Anyone here who already resolve this??

**Comment by pornel** [comment] 2017-05-26 12:12
Can you give more information how to reproduce this?

**Comment by pornel** [comment] 2017-05-26 12:16
The message contains error code -60008, which is errAuthorizationInternal 

https://lists.apple.com/archives/apple-cdsa/2007/Sep/msg00010.html

**Comment by cherpake** [comment] 2017-05-27 12:47
Reverted to Sparkle ver. 1.15.1 and it seems to be working fine now.
My guess it has something to do with 'Guided package installs'

**Comment by cherpake** [comment] 2017-05-27 12:52
Also it might be helpful to note that pkg was produced by Packages app: http://s.sudre.free.fr/Software/Packages/about.html

and you can download broken update from here:
https://www.cherpake.com/downloads/Remote-for-Mac-7.7.17.pkg-old.zip (it uses Sparkle 1.17.0

**Comment by pornel** [comment] 2017-06-02 21:52
Please try the latest build

**Comment by jezrielbajan** [comment] 2017-06-07 09:38
Still having the same issue on the latest build.

**Comment by sandercox** [comment] 2017-07-04 08:41
Hi we've been noticing this issue as well. After some debugging this morning I noticed one thing that is different between the two runs (the one that fails and the one that works):

In Console I see on a non-successful run:

process | message
--------|-----
Autoupdate | PID to listen: 8640
authd | Succeeded authorising right 'system.privilege.admin' by client '/PathToMyAppsCaches/AutoUpdater.app'
Autoupdate|Failed to perform final installation (and the error mentioned at topic start)

In Console I see on a successful run:

process | message
--------|-----
Autoupdate | PID to listen: 8690
authd | Succeeded authorising right 'system.privilege.admin' by client '/PathToMyAppsCaches/AutoUpdater.app'
authd | Succeeded authorising right 'system.privilege.admin' by client '/usr/libexec/security_authtrampoline'
security_authtrampoline | executing /PathToMyAppsCaches/AutoUpdater.app/Contents/MacOS/fileop

So apparently in the second case it's also authorising the security_authtrampoline no clue why though.

**Comment by glock45** [comment] 2017-07-06 10:21
hi, 

We had similar sympthoms (plus error saying: "MacOS error: -67008"). Downgrade to 1.15.1 did help.

**Comment by pornel** [comment] 2017-07-06 11:28
@glock45 Did you choose 1.15.1 specifically? That is, 1.16.0 is the first version you see this error on?

**Comment by glock45** [comment] 2017-07-06 12:22
@pornel  I have not touched 1.16.0. Just followed this comment: https://github.com/sparkle-project/Sparkle/issues/1079#issuecomment-304449835

**Comment by DivineDominion** [comment] 2017-07-18 15:34
Just wanted to chime in and report that my users report something similar, and I have this issue on my dev machine since updating to Sierra a few weeks ago, too. But sometimes it fails more often than on the first try (today it only succeeded on the 7th). Cannot pinpoint this to any log output at the moment but will try with the new release ASAP.

**Comment by fujisoft** [comment] 2017-07-19 13:17
Our users report the same problem. We are using Sparkle version 1.18.0.

**Comment by sandercox** [comment] 2017-07-24 10:02
In the mean time I have this on my dev machine as well, every first time I run the software after it is installed, and do an update check and receive updates I have this error.

Tried a build with some retries (3) on the authentication part but that didn't solve anything, just three times the password prompt and the same error in the end (the other times the error was there but suppressed).

Also tried to supply path to tool to run as instructed in the Apple documentation but still the same.
```
    
    AuthorizationItem rightItems[] = {
        // The right that allows us to run tools as root user
        {.name = kAuthorizationRightExecute, .valueLength = toolPathLength, .value = toolPath, .flags = 0}
    };
```

This was all tested based on the sparkle commit 043ad0464a99ab13bb48597b1968780764088b0e

**Comment by kjsakata** [comment] 2017-10-23 10:31
> In the mean time I have this on my dev machine as well, every first time I run the software after it is installed, and do an update check and receive updates I have this error.

I got same problem.

1. Install from Pkg and starting from postinstall script (open /Applications/Xxx.app)
2. update request and process and same error and fault.

but manually starting App and Update success. (Some related process is not correct permission when starting from Pkg)
postinstall script change to "sudo open Xxx.app" and fixed problem when run app after installed.

**Comment by zorgiepoo** [comment] 2021-03-22 07:35
The auth model in Sparkle 1 is fragile. I'm assuming this is fixed in Sparkle 2 or in a more recent OS update by now. If not, please open a new issue.

**Closed by zorgiepoo** 2021-03-22 07:35 UTC
