### ISSUE TITLE
User reports updating never finishes

### ISSUE THREAD

**Issue by gnachman** [sparkle-project/Sparkle#1339] opened 2019-01-06 23:33 UTC
See the original report here:

https://gitlab.com/gnachman/iterm2/issues/7397#note_127920128

It looks like the installer never finishes running. He found a bunch of messages in Console.app but they didn't look like errors to me. Are there any additional steps I can advise him to take to provide more diagnostics?

**Comment by kornelski** [comment] 2019-01-07 00:35
Does the installer, when run from command line, work?

This is what we run:

```sh
/usr/sbin/installer -verboseR -pkg path-to-update.pkg -target /
```

**Comment by gnachman** [comment] 2019-01-08 07:01
What's the proper value for `path-to-update.pkg`? Is that the zip file I publish in my appcast?

**Comment by kornelski** [comment] 2019-01-08 13:45
In your bug you've said installer, I assumed you mean Apple's `installer` command that installs `.pkg` packages. 

So the `path-to-update.pkg` is the unzipped `.pkg` from the update.

**Comment by kornelski** [comment] 2019-01-08 13:45
Which version of Sparkle are you using?

**Comment by gnachman** [comment] 2019-01-09 07:31
I'm on 1.17.

**Comment by fujisoft** [comment] 2019-02-11 13:05
Looks to be a duplicate of https://github.com/sparkle-project/Sparkle/issues/1079

**Comment by zorgiepoo** [comment] 2021-03-22 07:45
Might not be an issue anymore and no diagnostics to go off here, I assume this was not referring to pkg updates.

**Closed by zorgiepoo** 2021-03-22 07:45 UTC
