### ISSUE TITLE
the 'criticalUpdate' feature is just remove the skip and remind me later buttons?

### ISSUE THREAD

**Issue by gaojinhsu** [sparkle-project/Sparkle#1859] opened 2021-05-28 04:08 UTC
## Summary

What I want is a real force update, which means when I launch an old version app,  the update alert view should show up as soon as possible,  besides, the alert view is disabled to be  dismissed unless the install button is  clicked  to do the next step.

## Version
1.26.0

**Comment by zorgiepoo** [comment] 2021-05-28 05:52
Critical updates also get higher preference to showing an update alert more immediately (especially if updates are set to automatically download/install).

I think this was sort of discussed in #138. This is a feature request. I am not sure if this is a good idea, the window is also not modal.

Flushing out and fixing appcast selection on existing features is more of my priority right now rather than adding additional features. For example a critical update cannot presently only apply updating from less than a specific version.

**Comment by zorgiepoo** [comment] 2021-05-29 07:22
Thinking about this more, in my opinion having an update alert that cannot be skipped and shows up each time the scheduler kicks in is obstructive enough to forcing the user to update. One can disable closing the window (which is equivalent to remind me later) to be a little more obstructive, perhaps, but that may irritate the user.. I don't really want the window to be modal (preventing other parts of the app from being used).

**Comment by gaojinhsu** [comment] 2021-05-31 09:03
> Thinking about this more, in my opinion having an update alert that cannot be skipped and shows up each time the scheduler kicks in is obstructive enough to forcing the user to update. One can disable closing the window (which is equivalent to remind me later) to be a little more obstructive, perhaps, but that may irritate the user.. I don't really want the window to be modal (preventing other parts of the app from being used).

In some reason, I have to implement the "force" or "required" update, So I decide to implement it by myself, I change the SUUpdateAlert to modal, and it works, but when it comes to SUStatusController, the download session seems to be blocked. here is my code in 'SUUIBaseUpdateDriver.m'
 `- (void)downloadUpdate
{
    BOOL createdStatusController = NO;
    if (self.statusController == nil) {
        self.statusController = [[SUStatusController alloc] initWithHost:self.host];
        createdStatusController = YES;
    }
    
    [self.statusController beginActionWithTitle:SULocalizedString(@"Downloading update...", @"Take care not to overflow the status window.") maxProgressValue:0.0 statusText:nil];
    [self.statusController setButtonTitle:SULocalizedString(@"Cancel", nil) target:self action:@selector(cancelDownload:) isDefault:NO];
    [self.statusController setButtonEnabled:YES];
    
    if (createdStatusController) {
        if (self.updateItem.isRequiredUpdate) {
            NSWindow *window = self.statusController.window;
            [[NSApplication sharedApplication]runModalForWindow: window];
        } else {
            [self.statusController showWindow:self];
        }
    }
    
    [super downloadUpdate];
}`
any advice?

**Comment by zorgiepoo** [comment] 2021-05-31 22:15
1. If it meets your needs, just enable automatic downloading/installing of updates. This covers most cases and installs updates on quit except for when auth is needed (think non-admin user accounts).

2. Don't make the update UI modal. You do not want to prevent the user from quitting your app, even during an install-update-on-launch workflow. Hide the rest of your app UI instead and wait until the updater is done (in both cases when update is found to be downloaded/installed and when an update is not found; there's probably delegate methods here). You may only want to check for updates during launch in this case and opt out of automatic checking for updates. Sparkle does not provide a good UI in this case (I'm thinking of an app logo shown like Discord which takes a long time to launch..), but 2.x lets users plug in their own custom UI / user driver, although I'm still revising the API.

**Closed** 2021-09-06 19:08 UTC

**Comment by core-code** [comment] 2022-08-04 21:47
> One can disable closing the window (which is equivalent to remind me later)

how can we disable that? our users keep skipping the updates by closing the window even though they have `sparkle:criticalUpdate` set and we really need to prevent this. any ideas? thanks!

**Comment by zorgiepoo** [comment] 2022-08-05 00:40
It's not possible without forking Sparkle and making adjustments in say, `-[SUUpdateAlert windowDidLoad]`. Presently as discussed above, this is expected behavior for Sparkle. Technically users can still ignore the window if it's not closable. Make it modal and you may introduce other problems.

**Comment by zorgiepoo** [comment] 2022-08-05 00:51
Maybe disabling the close button for critical updates is OK.

**Comment by core-code** [comment] 2022-08-05 09:41
> It's not possible without forking Sparkle

thanks for the info

> no.. I don't think so.

why not? "critical" implies that the update is required and cannot be skipped. 
thats why the "skip" and "ignore" buttons are removed. removing those but keeping the close button is weird IMO. like a job half-done...

would it be possible to make that change either by default or optionally (enabled by some delegate methods)?

going "modal" is definitely a bad idea though.

**Comment by core-code** [comment] 2022-08-05 15:35
all our updates are manadatory. there is no choice. the app requires server support and most of the time if there is an update the existing version will stop working in one or two weeks anyway. so the only thing that leads to a really bad user experience is the existing ability for users to click the close button.

we don't want silent / background updates though as it is essential that people read the release notes.

i guess the only solution currently available in mainline Sparkle is just calling `checkForUpdatesInBackground` again if `didDismissUpdateAlertPermanently` gets called in response to the window closing. we'll implement just that for the time being.

**Comment by core-code** [comment] 2022-08-29 16:39
unfortunately you can check for a user closing the window in Sparkle 1.x with the `didDismissUpdateAlertPermanently` delegate method but in Sparkle 2.x the `userDidSkipThisVersion` is not called when the user closes Sparkles window

**Comment by core-code** [comment] 2022-08-29 17:35
the attached patch fixes a bug where `userDidSkipThisVersion` is not called because the relevant method passes `skipThisVersion` instead of `SPUUserUpdateChoiceSkip`

also it adds the new `userDidDismissThisVersion` delegates that can be used to learn if the user clicked "remind me later" or closed the window

[fix-diff-patch.txt](https://github.com/sparkle-project/Sparkle/files/9446782/fix-diff-patch.txt)

**Comment by zorgiepoo** [comment] 2022-08-30 02:24
> the attached patch fixes a bug where `userDidSkipThisVersion` is not called because the relevant method passes `skipThisVersion` instead of `SPUUserUpdateChoiceSkip`

I'm not following this. The patch does not apply for me on 2.x or to any version of Sparkle I know (briefly looking).

> also it adds the new `userDidDismissThisVersion` delegates that can be used to learn if the user clicked "remind me later" or closed the window. the other option instead of introducing a new method would be to re-add the "permanently" parameter to `userDidSkipThisVersion` and call it with NO for dismissals and YES for skips...
> 
> [fix-diff-patch.txt](https://github.com/sparkle-project/Sparkle/files/9446782/fix-diff-patch.txt)

I think this is probably a fine delegate addition if you were to open a PR.

**Comment by zorgiepoo** [comment] 2022-08-31 05:14
I added a task for dismissing callback #2250

I didn't see anything wrong with the skip callback, works over here.

**Comment by core-code** [comment] 2022-08-31 10:55
> I added a task for dismissing callback https://github.com/sparkle-project/Sparkle/issues/2250
 
thanks! 

> I didn't see anything wrong with the skip callback, works over here.

indeed, i think this was broken by some earlier change in my tree. sorry for the noise

**Comment by zorgiepoo** [comment] 2022-09-02 23:13
Checking for updates when the user dismisses the update alert is anyway a pretty bad idea. 

`didDismissUpdateAlertPermanently` in 1.x is called when the user chooses to install an update too, so it's not really intended for this purpose (it is similar in purpose to `-[SPUStandardUserDriverDelegate standardUserDriverWillFinishUpdateSession]` in 2.x but slightly different in behavior)

I can anyway expose the update alert window privately via #2255 before I commit to any sort of "mandatory update" solution that I would be happy with..

So you can make the window not closable if you want:

```swift
func standardUserDriverWillHandleShowingUpdate(_ handleShowingUpdate: Bool, forUpdate update: SUAppcastItem, state: SPUUserUpdateState) {
        // Maybe don't punish a user initiated check..
        // You could make this more sophisticated if you want, e.g. allowing window to be closeable for some N amount of times before making it "must update now"
        if !state.userInitiated && update.isCriticalUpdate && !update.isMajorUpgrade {
            self.updaterController.userDriver.activeUpdateAlert?.window?.styleMask.subtract(.closable)
        }
}
```

**Comment by core-code** [comment] 2022-09-05 11:01
thanks, exposing the window sounds like a good solution for the time being!

**Comment by core-code** [comment] 2022-09-15 23:26
thanks - disabling the closing of the window works fine now! for reference:


```
@interface SPUStandardUserDriver ()
@property (nonatomic) NSWindowController * _Nullable activeUpdateAlert;
@end

- (void)standardUserDriverWillHandleShowingUpdate:(BOOL)handleShowingUpdate forUpdate:(SUAppcastItem *)update state:(SPUUserUpdateState *)state
{    
    userDriver.activeUpdateAlert.window.styleMask  &= ~(NSWindowStyleMaskClosable | NSWindowStyleMaskMiniaturizable | NSWindowStyleMaskResizable);
}
```

**Comment by zorgiepoo** [comment] 2022-09-16 02:12
In 2.3 you can `#import <Sparkle/SPUStandardUserDriver+Private.h>` instead of re-declaring a category/method.
