### ISSUE TITLE
Incorrect EdDSA warning with signed dmg files?

### ISSUE THREAD

**Issue by lostminds** [sparkle-project/Sparkle#2041] opened 2021-12-14 09:47 UTC
## Summary

I'm trying out the new Sparkle 2.0.0rc1 to get ready to migrate to it when it's released in a future update of my app. I'm currently using codesigned dmgs (using apple codesigning and my developer signature) which I figured was a good alternative to EdDSA-signing archives since I wouldn't have to keep track of another set of keys and signing identity and I still need the signed dmgs for downloads. However, Sparkle 2.0 now gives me the following warning at launch: 

"Error: Serving updates without an EdDSA key and only using Apple Code Signing is deprecated and may be unsupported in a future release. Visit Sparkle's documentation for more information: https://sparkle-project.org/documentation/#3-segue-for-security-concerns"

Is this a bug? In other words, is it incorrectly warning about "only using Apple Code Signing", even tough the dmg files are also signed? Or is the warning correct that using signed dmgs for distributing updates will no longer be supported in future updates?

## Possible Fix

If this is a bug, I guess the fix would be to not show this warning even if there's no EdDSA in the appcast if the downloads are signed dmgs.

If it's not a bug, adding another level of signing (now three levels of code signing) seems a little excessive to me, if it's even possible to re-sign the signed dmg files with an additional EdDSA signature. Based on the segue-for-security-concerns page I can't figure out how I'd do it anyway. Since I already have signed dmg files for the app downloads I would like to keep using these for the updates as well, and my understanding is that they already offer a similar level of tamper protection?

## Version

2.0.0rc1

**Comment by zorgiepoo** [comment] 2021-12-15 03:19
To answer your question, it's intended behavior and not a bug. This policy was in 2.x since its inception and the deprecation notice landed in 1.27 as part of EdDSA migration work too.

We don't have any support for validating a matching Apple code signature from an archived dmg which may indeed offer similar level of protection. Although we also don't recommend serving disk images for updates because they can be less reliable and sometimes significantly slower to extract in a programmatic fashion (but they're fine and sometimes ideal for website distribution).

The one plus for EdDSA keys is that it allows key rotation of either the Developer ID keys or Sparkle keys. I've seen people needing to unexpectedly change their Apple signing ID in the past, and this rotation allows this.

**Comment by zorgiepoo** [comment] 2021-12-15 03:29
Also we use Sparkle's EdDSA keys for other installation types, other update archives better suited for updates, binary delta updates (discouraging EdDSA incentives not using these), and potentially may offer optional signing of appcasts and release notes in the future. So they're not quite going away.

**Comment by zorgiepoo** [comment] 2021-12-15 07:12
> We don't have any support for validating a matching Apple code signature from a dmg which may indeed offer similar level of protection (if it works; nobody has tried/tested it)

Out of curiosity I made a test to see if this would work but it turns out it doesn't; the system APIs we use to validate that the old app bundle identity matches with a new one doesn't work across signed disk images and app bundles, at least not as far as I could tell. So this is no use to us and I can't think of anything actionable here now.

As far as using Sparkle's tools: it's 1. generate keys, 2. use generate_appcast like usual, or use sign_update on the archive you serve to Sparkle if you don't use generate_appcast.

**Closed by zorgiepoo** 2021-12-15 07:12 UTC
