### ISSUE TITLE
SUUpdater shim aborts when no SUFeedURL is present when instantiated

### ISSUE THREAD

**Issue by johnwbyrd** [sparkle-project/Sparkle#1505] opened 2019-11-23 02:02 UTC
At some expense, I have discovered that SUUpdater shim in ui-separation-and-xpc silently fails in release mode on versions of MacOS 10.13 and earlier (but not 10.14), if the feed URL is not set when the SUUpdater object is created.

Previous SUUpdater behavior was to defer setting and testing the first update until requested via checkForUpdatesInBackup.  For situations where the SUFeedURL is set dynamically, the current implementation of requiring it to go in Info.plist is insufficient.

In release mode, Sparkle should NEVER call abort() due to run-time conditions, which it does all over the place.  Sparkle is merely update software.  The worst it should ever do at a client site is fail silently.  In release mode, please log errors instead of just dying on the main thread.

**Comment by jakob** [comment] 2019-12-15 19:56
I've tried to fix the issue by delaying the updater startup just like in Sparkle 1.x. I can no longer reproduce the crash, even when the feed URL is set in code.

Can you verify if the issue is fixed now?

I did not remove the abort() call, that's a separate issue.

**Comment by zorgiepoo** [comment] 2021-05-30 18:08
Resolved at some point.

**Closed by zorgiepoo** 2021-05-30 18:08 UTC
