### ISSUE TITLE
xcode 8 exporting developer id signed app fails due to autoupdate's bundle id

### ISSUE THREAD

**Issue by ConfusedVorlon** [sparkle-project/Sparkle#822] opened 2016-06-16 01:12 UTC
in xcode 8, the signing process tries to give every app a provisioning profile; even if it is developer-id signed.
This is to enable features like cloudkit in non app-store apps.

However, it requires that every app and sub-app has a unique bundle id, so the export fails with the message:

An App ID with identifier ' org.sparkle-project.Sparkle.Autoupdate' is not available. Please use a different string

I'm at wwdc and have spoken to folks on the xcode signing team. They have suggested that I file a radar (I have done so). 
It's possible that this behaviour will change in later releases, but I wouldn't bet on it!

I can't see an obvious fix that fits within the cocoapods system - but some script to change the id of the updater may be in order...

**Comment by ConfusedVorlon** [comment] 2016-06-16 01:14
to be clear - steps to reproduce

1) Mac OSX app
2) Include Sparkle
3) Archive the project
4) Export developer id signed version

expected: Rainbows
actual: `An App ID with identifier ' org.sparkle-project.Sparkle.Autoupdate' is not available. Please use a different string`

**Comment by zorgiepoo** [comment] 2016-06-16 02:35
Autoupdate.app is put into Sparkle's Resources directory, which is not a place that should be expecting code signed files. We include it un-signed (see #546 for more details on that). I don't know why Xcode should be complaining about it or even consider it for signing at all.

**Comment by zorgiepoo** [comment] 2016-06-16 03:03
..that aside, if this turns out to be an issue in the end I vote for archiving Autoupdate or obfuscating it some other way inside Sparkle because people tend to run into signing issues with it, and we more or less treat it as a piece of data and never launch the app directly from inside the framework.

Apparently Xcode 8's exporting process doesn't scan only for directories that should contain signed items though, and I'm curious whether or not Apple is going to change that.

**Comment by pornel** [comment] 2016-06-16 14:28
But we do launch it after copying to a tmp dir. I always assumed that launching it then would require it being signed (if the system doesn't allow running apps from unidentified developers).

Unless you're suggesting signing and then obfuscating signed app?

**Comment by zorgiepoo** [comment] 2016-06-16 21:40
Let me clarify: If you drop Sparkle into an application target that is set up to code sign Sparkle when copying the framework into the application, Xcode will *not* code sign Autoupdate.app which is *expected behavior*. This is partly because Autoupdate is not in a directory that should contain code signed items, which in turns mean that Autoupdate should not be signed. Aside from this, I have painfully learned due to how the tooling works that nothing that should be signed should reside inside a framework.

As for launching it after copying it into ~/Library/Caches/ somewhere, we release the quarantine before launching the app, which may not even be necessary because we spawn a task rather than going through LaunchServices, but better be safe than sorry.

**Comment by ConfusedVorlon** [comment] 2016-06-17 00:00
I just tested this on a 100% clean project and do see the error

1. Use xcode Version 8.0 beta (8S128d)
2. create new cocoa app
3. pod init
4. add sparkle to podfile
5. pod install
6. add sparkle codesigning build script
7. archive
8. export developer id signed application

result:

![2016-06-16 04 58 53 pm](https://cloud.githubusercontent.com/assets/586910/16136943/aec7305a-33e3-11e6-9f53-6905b00bb9d7.png)

**Comment by zorgiepoo** [comment] 2016-06-17 00:15
Please report to Apple that it should only respect [standard locations for code (Table 3)](https://developer.apple.com/library/mac/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG404). Autoupdate is intended to be a resource in Sparkle's case. I am interested in what they would have to say back. What radar number did you file?

That code signing build script may not be necessary by the way (#709).

**Comment by ConfusedVorlon** [comment] 2016-06-17 00:36
I have submitted a bug ( id 26827710 ) and have linked to this thread.

**Comment by mackworth** [comment] 2016-07-08 17:28
Still present in beta 2

**Comment by mackworth** [comment] 2016-07-08 19:41
Unfortunately, this is still present in XCode 8, beta 2

**Comment by mileswd** [comment] 2016-07-18 21:57
This also appears to be still present in Xcode 8, beta 3.

**Comment by zorgiepoo** [comment] 2016-07-22 01:20
I had duped the rdar a while back (26883571). If the issue persists, I suggest filing a duplicate bug report to Apple.

You may be able to work around it temporarily by changing the bundle id of Autoupdate. I'm not sure I'm happy with the approach I mentioned before for archiving Autoupdate..

**Comment by mileswd** [comment] 2016-08-02 00:36
As far as I can tell, this issue appears to be resolved in Xcode 8, beta 4.

**Comment by zorgiepoo** [comment] 2016-11-11 02:21
This seems to work for me using Xcode 8.1 on Sierra

**Comment by Coladia** [comment] 2016-11-27 21:05
I'm still having the issue with Xcode 8.1

**Comment by zorgiepoo** [comment] 2016-11-30 23:05
@Coladia How are you incorporating and building with Sparkle? I can't reproduce this following the steps above (minus adding the sparkle codesigning build script if you use cocoapods; don't do that).

**Comment by Coladia** [comment] 2016-11-30 23:24
I build Sparkle and I include the framework generated to my project.

**Comment by zorgiepoo** [comment] 2016-12-01 00:12
Not really sure why I can't reproduce it. I am assuming you're using your Developer ID certificate. Can you reproduce the issue if you use one of the Sparkle.framework distributions that *we* [have built](https://github.com/sparkle-project/Sparkle/releases)? (usually don't have to build Sparkle yourself).

**Comment by zorgiepoo** [comment] 2016-12-19 17:01
FYI, since this wasn't immediately obvious to me:

Apple really wants developers to distribute applications using the 'Archive' feature and Organizer window. After the archive is done, you can export it using your developer ID certificate, which is when the application gets *resigned*. Currently in Xcode 8 (subject to change?), the timestamp server is only initiated during this export process (otherwise the timestamp option is disabled unless you sign via command line).

The implications of this are the following: in many cases, you ought to not have to apply code signing settings during normal Debug/Release builds in Xcode. Even in cases where you need signing (i.e, special requirements), an ad-hoc or self-signed certificate could be appropriate for such builds. Developer ID is appropriate when exporting your application after archiving.

Note the way Xcode decides what to sign in a bundle during an export also differs from how 'Code Sign on Copy' works.

**Comment by joshorr** [comment] 2017-01-06 23:07
As a work around: If you go into you archive (right click the newly built archive in organizer) and then you go into it's package from the finder (right-click->show package contents) and then go into your app, and then the Frameworks folder, and then the sparkle framework, and then eventually get to the Autoupdate.app, and then modify it's info.plist. Prepend it's bundle ID with your unique string (ie: com.somecompany).  Save that and then do an export and sign via Developer ID.  The export should work correctly.  Now, undo the info.plist change.  You can now export fine, and continue to do so until xcode at some point in the future needs to create new provision profiles for you. At that point you will have to do this again.

Works for me every time.

**Comment by imWildCat** [comment] 2021-07-09 01:00
Any updates on this issue?

**Comment by zorgiepoo** [comment] 2021-07-09 01:10
Moving discussion in #1885, there's some old issues here that might have been resolved and some discussion that may be confusing / not accurate now.

**Closed by zorgiepoo** 2021-07-09 01:10 UTC
